// Click on button to start quiz
// Done 

// Show question and answers 
// Done

// After answering question, check if answer is correct or not
// EventHandler (click) to check value of multiple choice
// Check against correct answers ?

// If correct - change UI to show that it was correct (flash green ?)
// documentGetElementbyID change styling

// If incorrect - flashes red, incorrect 
// documentGetElementbyID change styling

